import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "./apollo-wrapper";
import Header from "./components/Header";

import { ThemeProvider } from '@mui/material/styles';
import theme from './src/theme';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider theme={theme}>
        <Header></Header>
        <ApolloWrapper>{children}</ApolloWrapper>
       </ThemeProvider>

        </body>
    </html>
  );
}
